//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Mang_Sampah.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public int UserAccountId { get; set; }
        public int PartnerAccountId { get; set; }
        public System.DateTime OrderReqTime { get; set; }
        public string Description { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual PartnerAccount PartnerAccount { get; set; }
    }
}
