//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Mang_Sampah.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerAccount : Account
    {
        public string CompanyName { get; set; }
    }
}
