//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Mang_Sampah.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public int PostsId { get; set; }
        public string Content { get; set; }
        public int LikesCount { get; set; }
        public System.DateTime UploadTime { get; set; }
        public int AccountId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
